function getStickerImage(sticker) {
    if(sticker === ":CAT:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/CAT/PNG/cat_with_border.png'></img>"};
    if(sticker === ":FAIL:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/FAIL/PNG/fail_with_border.png'></img>"}
    if(sticker === ":HYPE:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/HYPE/PNG/hype_with_border.png'></img>"}
    if(sticker === ":PANTS_1:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/PANTS/PNG/PANTS_1_with_frame.png'></img>"}
    if(sticker === ":PANTS_2:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/PANTS/PNG/PANTS_2_with_frame.png'></img>"}
    if(sticker === ":PISS:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/PISS/PNG/piss_with_frame.png'></img>"}
    if(sticker === ":PREGNANT_MAN_ASIA:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/pregnant%20man/png/Pregnant%20man_white%20border_asia.png'></img>"}
    if(sticker === ":PREGNANT_MAN_BLACK_HAIR:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/pregnant%20man/png/Pregnant%20man_white%20border_black%20hair.png'></img>"}
    if(sticker === ":PREGNANT_MAN_BLACK_SKIN:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/pregnant%20man/png/Pregnant%20man_white%20border_black%20skin.png'></img>"}
    if(sticker === ":PREGNANT_MAN_BLONDE:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/pregnant%20man/png/Pregnant%20man_white%20border_blondie.png'></img>"}
    if(sticker === ":PREGNANT_MAN_RED_HAIR:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/pregnant%20man/png/Pregnant%20man_white%20border_red%20hair%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.png'></img>"}
    if(sticker === ":PREGNANT_WOMAN_BLACK_HAIR_GREEN_SHIRT:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/pregnant%20woman/png/Pregnant%20woman_white_border_black%20hair%20green%20shirt.png'></img>"}
    if(sticker === ":PREGNANT_WOMAN_BLACK_HAIR:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/pregnant%20woman/png/Pregnant%20woman_white_border_black%20hair.png'></img>"}
    if(sticker === ":PREGNANT_WOMAN_BLACK_SKIN:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/pregnant%20woman/png/Pregnant%20woman_white_border_black%20woman.png'></img>"}
    if(sticker === ":PREGNANT_WOMAN_BLONDE:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/pregnant%20woman/png/Pregnant%20woman_white_border_blondie.png'></img>"}
    if(sticker === ":PREGNANT_WOMAN_BROWN_HAIR:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/pregnant%20woman/png/Pregnant%20woman_white_border_brown%20hair.png'></img>"}
    if(sticker === ":PREGNANT_WOMAN_RED_HAIR:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/pregnant%20woman/png/Pregnant%20woman_white_border_red%20hair%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.png'></img>"}
    if(sticker === ":ROCKET_SPACEMAN:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/ROCKET%20SPACEMAN/PNG/rocket-spaceman_with-border.png'></img>"}
    if(sticker === ":SALTY:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/SALTY/PNG/salty.png'></img>"}
    if(sticker === ":SICK_FLAME:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/SICK/PNG/sick2_with_border.png'></img>"}
    if(sticker === ":SICK_SKULL:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/SICK/PNG/with%20borderdark%20with%20frame.png'></img>"}
    if(sticker === ":SLIME:") {return "<img src'https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/SLIME/PNG/slime_with_frame.png'></img>"}
    if(sticker === ":SPAGHETTI_BATH:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/SPHAGETTI%20BATH/PNG/sphagetti%20bath_with_frame.png'></img>"}
    if(sticker === ":THUG_LIFE:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/THUG%20LIFE/PNG/thug_life_with_border_clean.png'></img>"}
    if(sticker === ":WHUUT:") {return "<img src='https://thumbnails.odysee.com/optimize/s:0:100/quality:85/plain/https://static.odycdn.com/stickers/WHUUT/PNG/whuut_with-frame.png'></img>"}
}

module.exports.getStickerImage = getStickerImage;